package com.flabser.exception;

public enum AuthFailedExceptionType {
	NO_USER_SESSION, PASSWORD_OR_LOGIN_INCORRECT, INCOMPLETE_REGISTRATION, ACCESS_DENIED, NO_ASSOCIATED_SESSION_FOR_THE_TOKEN, UNKNOWN_STATUS, USER_WAS_DELETED;
}
