package com.flabser.exception;

public enum ServerServiceExceptionType {
	FORMDATA_INCORRECT, OLD_PWD_INCORRECT, FORMDATA_INCORRECT_FOR_PARSER, WEAK_PASSWORD, USER_EXISTS, EMAIL_IS_INCORRECT, SERVER_ERROR, USER_NOT_FOUND, UNKNOWN_APPLICATION_TEMPLATE, VALUE_IS_EMPTY, UNKNOWN_USER_STATUS
}
