package com.flabser.exception;

public enum ServerServiceWarningType {
	VERIFY_EMAIL_SENDING_ERROR, RESET_PASSWORD_SENDING_ERROR, RESET_PASSWORD_ALREADY_SENT, UNKNOWN_USER_STATUS, INVITATION_SENDING_ERROR, USER_ALREADY_REGISTERED

}
