package com.flabser.script;

public enum _ExceptionType {
	NO_PERMISSION_TO_READ_THE_DOCUMENT, FORMDATA_INCORRECT, NOT_UNIQUE_USERNAME, SCRIPT_ENGINE_ERROR, ATTACHMENT_FIELD_NOT_FOUND,
	DOCUMENT_FIELD_NOT_FOUND, UNKNOWN_MACRO, CONSTRUCTOR_UNDEFINED, DOCUMENT_FIELD_CAUSED_ERROR, COMPLEX_OBJECT_ERROR,
    NO_PERMISSION_TO_DELETE_DOCUMENT, DOCUMENT_DELETING_ERROR, MAIL_AGENT_ERROR, USERNAME_DOES_NOT_CHANGE
}
