package com.flabser.users;

public enum AuthFailedExceptionType {
	NO_USER_SESSION, PASSWORD_OR_LOGIN_INCORRECT, NOT_FOUND, INCOMPLETE_REGISTRATION, ACCESS_DENIED, NO_ASSOCIATED_SESSION_FOR_THE_TOKEN;
}
