package com.flabser.supplier;

public enum Macro {
	AVAILABLE_LANGS, 
	AVAILABLE_SKINS,
	AVAILABLE_APPLICATIONS, 
	UNKNOWN_MACRO,
	HAS_ATTACHMENT,
	HAS_RESPONSE,
	VIEW_TEXT,
	AUTHOR,
	MACRO_MAINDOCID,
	CURRENT_USER,
	CURRENT_USER_DEPARTMENT,
	MACRO_CURRENT_TIME,
	MACRO_CURRENT_USER_ID,
	MACRO_MAINDOCNOTESID,
	EXECUTORS,
	COORD_BLOCKS,   
	RECIPIENTS,
	VERSIONS,
	UNDEFINED,
	CURRENT_USER_ROLES,
	SERVER_VERSION,
	CURRENT_TIME,
	APPLICATION_TYPE,APPLICATION_LOGO,
	CONTROL,
    REPORT,
	APP_URL, APPLICATION_NAME,
	FILTER, ORG_NAME, ALL_APPLICATIONS, CURRENT_USER_POSITION, APPLICATION_ROLES, COMPILATION_TIME, APPLICATION_GROUPS
	
}
