package com.flabser.supplier;

public enum SourceSupplierContextType {
	UNKNOWN,
	SIMPLE,
	APP_ENVIRONMENT,
	VOCABULARY,
	DOCUMENT,
	DOCUMENT_WITH_LANG,
	DATABASE,
	DEFAULT_FORM,
	SHOW_FORM,
	SIMPLE_WITH_LANG
}
