package com.flabser.util;

public enum ResponseType {
	SAVE_FORM, 
	SAVE_FORM_OF_USER_PROFILE, 
	DO_PROVIDER_HANDLER, 
	RESULT_OF_HANDLER_SCRIPT, 
	DELETE_ORGANIZATION, 
	UPLOAD_FILE,
	NEXT_COORD, 
	TO_SIGN, 
	START_COORD, 
	STOP_COORD, 
	RESET_EXECUTOR, 
	DELETE_DOCUMENT, 
	UNDELETE_DOCUMENT, 
	DELETE_USER, 
	RESET_RULES, 
	RESET_XSLT, 
	SAVE_FORM_OF_RULE,
	AUTHENTICATION, SUPPLY_LOGIN_QUESTION, EXCEPTION, DO_HANDLER_THREAD, SHOW_FILE_AFTER_HANDLER_FINISHED, OPEN_FORM, RESULT_OF_PAGE_SCRIPT, RESULT_OF_HANDLER_SERVICE, CLEAR_DOCUMENTS, UPDATE_FT_INDEX, RESULT_OF_SIGN_PROVIDER_SERVICE, DO_SCHEDULED_HANDLER
}
