package com.flabser.servlets;

public enum ProviderExceptionType {
	SERVER,AUTHFAILED,INTERNAL,RULENOTFOUND,XSLTNOTFOUND,DATAENGINERROR,DOCUMENTEXCEPTION,XSLT_TRANSFORMATOR_ERROR,PROVIDERERROR, LOGINERROR, CLASS_NOT_FOUND_EXCEPTION, WEBFORM_VALUE_EXCEPTION, LOGOUTERROR
}
